import math as m
print("pi:", m.pi)
print("e:", m.e)
print("tau:", m.tau)
print("infinity:", m.inf)
print("not a number:", m.nan)
print("ceil:", m.ceil(5.5))
print("floor:", m.floor(5.5))
print("factorial:", m.factorial(5))
print("power:", m.pow(2,3))
print("absolute value:", m.fabs(-5))
print("modulo:", m.fmod(10,5))
print("sum:", m.fsum([1,2,3]))
print("square root:", m.sqrt(25))
print("truncate:", m.trunc(10.23456789))
